[
  {
    "id": "faith-foundations",
    "name": "Faith Foundations",
    "description": "Build an unshakeable foundation of faith through key Scripture passages.",
    "subtype": "topic",
    "icon": "🙏",
    "color": "#5B4FCF",
    "visibility": "public",
    "content": [
      { "reference": "Hebrews 11:1",       "title": "What faith is",             "focus": "Faith is the substance of things hoped for, the evidence of things not seen." },
      { "reference": "Romans 10:17",        "title": "Faith comes by hearing",    "focus": "Faith grows through consistent, daily engagement with God's Word." },
      { "reference": "Matthew 17:20",       "title": "Mustard seed faith",        "focus": "Even the smallest genuine faith can move what seems impossible." },
      { "reference": "Proverbs 3:5-6",      "title": "Trust with all your heart", "focus": "Lean on God's understanding, not your own limited perspective." },
      { "reference": "2 Corinthians 5:7",   "title": "Walk by faith not sight",   "focus": "Living by faith means acting before you can fully see the outcome." },
      { "reference": "Isaiah 40:31",        "title": "Renew your strength",       "focus": "Those who wait on the Lord will soar — they do not grow weary." },
      { "reference": "Psalm 46:1-2",        "title": "God is our refuge",         "focus": "Even when everything shakes, God is a firm and stable foundation." },
      { "reference": "Mark 11:24",          "title": "Believe you have received", "focus": "Pray with expectation that God has already answered." },
      { "reference": "Hebrews 11:6",        "title": "Without faith impossible",  "focus": "Those who come to God must believe he rewards those who seek him." },
      { "reference": "Romans 4:20-21",      "title": "Abraham's faith",           "focus": "He did not waver — fully persuaded God would act on his promise." },
      { "reference": "James 1:3",           "title": "Testing grows faith",       "focus": "Trials are the training ground where faith becomes strong." },
      { "reference": "Matthew 14:28-31",    "title": "Peter walks on water",      "focus": "Faith steps out. Doubt sinks. Keep your eyes fixed on Jesus." },
      { "reference": "Psalm 37:3-4",        "title": "Trust and delight",         "focus": "Delight in God and he gives you the desires of your heart." },
      { "reference": "Lamentations 3:22-23","title": "New every morning",         "focus": "God's faithfulness is the ground on which your faith stands." },
      { "reference": "John 11:40",          "title": "See the glory of God",      "focus": "If you only believe, you will see what God can do." },
      { "reference": "1 John 5:4",          "title": "Overcomes the world",       "focus": "Your faith is the victory that overcomes every obstacle." },
      { "reference": "Hebrews 12:2",        "title": "Fix your eyes on Jesus",    "focus": "Jesus is both the author and the finisher of your faith." },
      { "reference": "Habakkuk 3:17-18",    "title": "Yet I will rejoice",        "focus": "Real faith praises God even before the breakthrough comes." },
      { "reference": "Revelation 2:10",     "title": "Faithful unto the end",     "focus": "Hold on. A crown of life awaits those who remain faithful." },
      { "reference": "Numbers 23:19",       "title": "God does not lie",          "focus": "Every promise God has spoken, he will fulfil without fail." }
    ]
  },
  {
    "id": "identity-in-christ",
    "name": "Identity in Christ",
    "description": "Discover who God says you are — chosen, loved, and set apart.",
    "subtype": "topic",
    "icon": "✨",
    "color": "#E8A838",
    "visibility": "public",
    "content": [
      { "reference": "John 1:12",          "title": "Child of God",                  "focus": "You have been given the right to be called God's very own child." },
      { "reference": "Ephesians 1:4-5",    "title": "Chosen and adopted",            "focus": "Before the world began, God chose you and adopted you as his own." },
      { "reference": "2 Corinthians 5:17", "title": "New creation",                  "focus": "Your old self is gone. Everything is brand new in Christ." },
      { "reference": "1 Peter 2:9",        "title": "Royal and chosen",              "focus": "You are chosen, royal, holy, and belonging to God himself." },
      { "reference": "Romans 8:17",        "title": "Heirs with Christ",             "focus": "You are not just saved — you are a co-heir with Jesus." },
      { "reference": "Galatians 3:26",     "title": "Sons of God through faith",     "focus": "Faith in Christ gives you full standing as a child of God." },
      { "reference": "Ephesians 2:10",     "title": "God's masterpiece",             "focus": "You are his handiwork, created for good works he prepared for you." },
      { "reference": "Colossians 2:10",    "title": "Complete in Christ",            "focus": "In him you are made complete. You lack nothing in Christ Jesus." },
      { "reference": "Isaiah 43:1",        "title": "I have called you by name",     "focus": "You are known, named, and personally claimed by God." },
      { "reference": "Romans 8:1",         "title": "No condemnation",               "focus": "There is zero guilt or shame for those who are in Christ Jesus." },
      { "reference": "Zephaniah 3:17",     "title": "He delights in you",            "focus": "God rejoices over you with singing. You bring him genuine joy." },
      { "reference": "Psalm 139:13-14",    "title": "Fearfully and wonderfully made","focus": "Every detail of you was crafted intentionally and lovingly by God." },
      { "reference": "Romans 8:38-39",     "title": "Nothing can separate you",      "focus": "Absolutely nothing can separate you from the love of God in Christ." },
      { "reference": "Jeremiah 29:11",     "title": "Plans to prosper you",          "focus": "God has future plans for you — plans of hope, not of harm." }
    ]
  },
  {
    "id": "prayer-life",
    "name": "A Life of Prayer",
    "description": "Deepen your prayer life through foundational Scripture on talking with God.",
    "subtype": "topic",
    "icon": "🕊️",
    "color": "#4A7C5F",
    "visibility": "public",
    "content": [
      { "reference": "Matthew 6:9-13",       "title": "The Lord's Prayer",           "focus": "Jesus gave us the model — adoration, surrender, petition, protection." },
      { "reference": "Philippians 4:6-7",    "title": "Prayer and peace",            "focus": "When you pray instead of worry, God's peace stands guard over you." },
      { "reference": "1 Thessalonians 5:17", "title": "Pray without ceasing",        "focus": "Prayer is not just a formal act — it is a constant conversation with God." },
      { "reference": "James 5:16",           "title": "Prayer of the righteous",     "focus": "Sincere prayer from a right heart is tremendously powerful." },
      { "reference": "Jeremiah 33:3",        "title": "Call to me",                  "focus": "God's personal invitation: call to him and he will answer in great ways." },
      { "reference": "Luke 18:1-8",          "title": "The persistent widow",        "focus": "Don't give up on prayer. Keep coming. God will answer." },
      { "reference": "Romans 8:26",          "title": "Spirit intercedes",           "focus": "When you don't know how to pray, the Spirit prays for you." },
      { "reference": "John 15:7",            "title": "Ask what you will",           "focus": "Abiding in Christ aligns your desires with his will." },
      { "reference": "Matthew 21:22",        "title": "Whatever you ask in faith",   "focus": "Believing prayer connects to unlimited divine possibility." },
      { "reference": "Psalm 62:8",           "title": "Pour out your heart",         "focus": "God is a refuge — pour every burden and feeling before him." },
      { "reference": "Hebrews 4:16",         "title": "Come boldly",                 "focus": "You can approach God's throne with full confidence and freedom." },
      { "reference": "1 John 5:14-15",       "title": "Confidence in prayer",        "focus": "If we ask according to his will, he hears us — and we have what we asked." },
      { "reference": "Daniel 6:10",          "title": "Daniel prays three times",    "focus": "A life of faithful prayer continues even under pressure and opposition." },
      { "reference": "Psalm 17:6",           "title": "I call to you",               "focus": "Simple, direct, personal calling on God is the very essence of prayer." }
    ]
  },
  {
    "id": "peace-and-anxiety",
    "name": "Peace Over Anxiety",
    "description": "Exchange worry for God's peace through Scripture that speaks directly to fear.",
    "subtype": "topic",
    "icon": "🌿",
    "color": "#7CB9E8",
    "visibility": "public",
    "content": [
      { "reference": "Philippians 4:6-7",  "title": "Do not be anxious",          "focus": "Prayer is the direct exchange — bring worry, receive peace." },
      { "reference": "Isaiah 41:10",       "title": "Do not fear",                "focus": "God promises to strengthen, help, and uphold you with his hand." },
      { "reference": "John 14:27",         "title": "My peace I give you",        "focus": "The peace Jesus gives is unlike anything the world can offer." },
      { "reference": "Psalm 23:4",         "title": "Through the valley",         "focus": "Even in your darkest season, God walks right beside you." },
      { "reference": "1 Peter 5:7",        "title": "Cast your anxiety",          "focus": "God invites you to give every single worry over to him." },
      { "reference": "Matthew 6:34",       "title": "Do not worry about tomorrow","focus": "Anxiety lives in the future. God meets you in the present moment." },
      { "reference": "Psalm 46:10",        "title": "Be still and know",          "focus": "Sometimes the most faithful act is to stop striving and simply rest." },
      { "reference": "2 Timothy 1:7",      "title": "Spirit of power",            "focus": "Fear does not come from God. Power, love, and clarity are from him." },
      { "reference": "Isaiah 26:3",        "title": "Perfect peace",              "focus": "Fix your mind on God and he keeps you in perfect, unbroken peace." },
      { "reference": "Romans 5:1",         "title": "Peace with God",             "focus": "Through faith you have full and complete peace with your Creator." },
      { "reference": "Psalm 34:4",         "title": "He delivered me",            "focus": "Seek God honestly and he will free you from all your fears." },
      { "reference": "Matthew 11:28-30",   "title": "Come to me",                 "focus": "Jesus personally and warmly invites the burdened to rest in him." }
    ]
  },
  {
    "id": "wisdom-for-life",
    "name": "Wisdom for Life",
    "description": "Walk in God's understanding through the key wisdom passages of Scripture.",
    "subtype": "topic",
    "icon": "💡",
    "color": "#E8A838",
    "visibility": "public",
    "content": [
      { "reference": "Proverbs 1:7",          "title": "Fear of the Lord",          "focus": "The beginning of all wisdom is reverence and respect for God." },
      { "reference": "James 1:5",             "title": "Ask for wisdom",            "focus": "God gives wisdom generously to all who ask him in faith." },
      { "reference": "Proverbs 3:5-7",        "title": "Trust in the Lord",         "focus": "Lean on God's understanding, not your own limited view." },
      { "reference": "Ecclesiastes 12:13",    "title": "The conclusion",            "focus": "Fear God and keep his commandments — this is the whole duty of humankind." },
      { "reference": "Psalm 111:10",          "title": "Wisdom begins here",        "focus": "Understanding comes to those who reverence and obey God." },
      { "reference": "Colossians 3:16",       "title": "Let the word dwell",        "focus": "Let Scripture live richly in you as the source of all wisdom." },
      { "reference": "Proverbs 4:7",          "title": "Get wisdom",                "focus": "Though it costs everything, get wisdom — it is the principal thing." },
      { "reference": "Isaiah 55:8-9",         "title": "My ways are higher",        "focus": "God's thoughts and plans operate at a completely different level." },
      { "reference": "1 Corinthians 1:25",    "title": "Foolishness of God",        "focus": "What seems foolish to the world is wiser than all human wisdom." },
      { "reference": "Romans 11:33",          "title": "Depth of riches",           "focus": "God's wisdom and knowledge are unsearchable and beyond finding out." }
    ]
  }
]